modLoader="javafml"
license="All Rights Reserved"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Glitchfiend/ToughAsNails/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tough-as-nails"
logoFile="tan_logo.png"

[[mods]]
    modId="toughasnails"
    version="${file.jarVersion}"
    displayName="Tough As Nails"
	authors="Adubbz, Forstride"
    description="Adds features to enhance survival mode and increase the game's difficulty."

[[dependencies.toughasnails]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"