modLoader="javafml"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Glitchfiend/ToughAsNails/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tough-as-nails"
logoFile="tan_logo.png"

[[mods]]
    modId="toughasnails"
    version="${version}"
    displayName="Tough As Nails"
	authors="Adubbz, Forstride"
    description='''
    Adds features to enhance survival mode and increase the game's difficulty.
    '''

[[dependencies.toughasnails]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"